[build]
  command = "pip install -r requirements.txt && python -m pip install --upgrade pip && python -m pip install gunicorn"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
