[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt"
  publish = "static"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9.0"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
